#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVien.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDoanVien")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDangKy(DangKy instance);
    partial void UpdateDangKy(DangKy instance);
    partial void DeleteDangKy(DangKy instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertDoanVien(DoanVien instance);
    partial void UpdateDoanVien(DoanVien instance);
    partial void DeleteDoanVien(DoanVien instance);
    partial void InsertSuKien(SuKien instance);
    partial void UpdateSuKien(SuKien instance);
    partial void DeleteSuKien(SuKien instance);
    partial void InsertMuaAo(MuaAo instance);
    partial void UpdateMuaAo(MuaAo instance);
    partial void DeleteMuaAo(MuaAo instance);
    partial void InsertDeXuat(DeXuat instance);
    partial void UpdateDeXuat(DeXuat instance);
    partial void DeleteDeXuat(DeXuat instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyDoanVienConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangKy> DangKies
		{
			get
			{
				return this.GetTable<DangKy>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<DoanVien> DoanViens
		{
			get
			{
				return this.GetTable<DoanVien>();
			}
		}
		
		public System.Data.Linq.Table<SuKien> SuKiens
		{
			get
			{
				return this.GetTable<SuKien>();
			}
		}
		
		public System.Data.Linq.Table<MuaAo> MuaAos
		{
			get
			{
				return this.GetTable<MuaAo>();
			}
		}
		
		public System.Data.Linq.Table<DeXuat> DeXuats
		{
			get
			{
				return this.GetTable<DeXuat>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DoanVien_Get_SuKien")]
		public ISingleResult<DoanVien_Get_SuKienResult> DoanVien_Get_SuKien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDDoanVien", DbType="Int")] System.Nullable<int> iDDoanVien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDDoanVien);
			return ((ISingleResult<DoanVien_Get_SuKienResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKy")]
	public partial class DangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDangKy;
		
		private int _IDSuKien;
		
		private int _IDDoanVien;
		
		private System.DateTime _NgayDangKy;
		
		private EntityRef<DoanVien> _DoanVien;
		
		private EntityRef<SuKien> _SuKien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDangKyChanging(int value);
    partial void OnIDDangKyChanged();
    partial void OnIDSuKienChanging(int value);
    partial void OnIDSuKienChanged();
    partial void OnIDDoanVienChanging(int value);
    partial void OnIDDoanVienChanged();
    partial void OnNgayDangKyChanging(System.DateTime value);
    partial void OnNgayDangKyChanged();
    #endregion
		
		public DangKy()
		{
			this._DoanVien = default(EntityRef<DoanVien>);
			this._SuKien = default(EntityRef<SuKien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDangKy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDangKy
		{
			get
			{
				return this._IDDangKy;
			}
			set
			{
				if ((this._IDDangKy != value))
				{
					this.OnIDDangKyChanging(value);
					this.SendPropertyChanging();
					this._IDDangKy = value;
					this.SendPropertyChanged("IDDangKy");
					this.OnIDDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSuKien", DbType="Int NOT NULL")]
		public int IDSuKien
		{
			get
			{
				return this._IDSuKien;
			}
			set
			{
				if ((this._IDSuKien != value))
				{
					if (this._SuKien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSuKienChanging(value);
					this.SendPropertyChanging();
					this._IDSuKien = value;
					this.SendPropertyChanged("IDSuKien");
					this.OnIDSuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDoanVien", DbType="Int NOT NULL")]
		public int IDDoanVien
		{
			get
			{
				return this._IDDoanVien;
			}
			set
			{
				if ((this._IDDoanVien != value))
				{
					if (this._DoanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDoanVienChanging(value);
					this.SendPropertyChanging();
					this._IDDoanVien = value;
					this.SendPropertyChanged("IDDoanVien");
					this.OnIDDoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoanVien_DangKy", Storage="_DoanVien", ThisKey="IDDoanVien", OtherKey="ID", IsForeignKey=true)]
		public DoanVien DoanVien
		{
			get
			{
				return this._DoanVien.Entity;
			}
			set
			{
				DoanVien previousValue = this._DoanVien.Entity;
				if (((previousValue != value) 
							|| (this._DoanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoanVien.Entity = null;
						previousValue.DangKies.Remove(this);
					}
					this._DoanVien.Entity = value;
					if ((value != null))
					{
						value.DangKies.Add(this);
						this._IDDoanVien = value.ID;
					}
					else
					{
						this._IDDoanVien = default(int);
					}
					this.SendPropertyChanged("DoanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuKien_DangKy", Storage="_SuKien", ThisKey="IDSuKien", OtherKey="ID", IsForeignKey=true)]
		public SuKien SuKien
		{
			get
			{
				return this._SuKien.Entity;
			}
			set
			{
				SuKien previousValue = this._SuKien.Entity;
				if (((previousValue != value) 
							|| (this._SuKien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SuKien.Entity = null;
						previousValue.DangKies.Remove(this);
					}
					this._SuKien.Entity = value;
					if ((value != null))
					{
						value.DangKies.Add(this);
						this._IDSuKien = value.ID;
					}
					else
					{
						this._IDSuKien = default(int);
					}
					this.SendPropertyChanged("SuKien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private int _GioiTinh;
		
		private string _UserName;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(int value);
    partial void OnGioiTinhChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Int NOT NULL")]
		public int GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanVien")]
	public partial class DoanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private bool _GioiTinh;
		
		private System.DateTime _NgayVaoDoan;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _Password;
		
		private string _NoiVaoDoan;
		
		private string _MSSV;
		
		private int _XepLoai;
		
		private System.Nullable<decimal> _NhanThucChinhTri;
		
		private System.Nullable<decimal> _ChuyenMonNghiepVu;
		
		private System.Nullable<decimal> _RenLuyenCaNhan;
		
		private System.Nullable<bool> _LaBiThu;
		
		private EntitySet<DangKy> _DangKies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnNgayVaoDoanChanging(System.DateTime value);
    partial void OnNgayVaoDoanChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNoiVaoDoanChanging(string value);
    partial void OnNoiVaoDoanChanged();
    partial void OnMSSVChanging(string value);
    partial void OnMSSVChanged();
    partial void OnXepLoaiChanging(int value);
    partial void OnXepLoaiChanged();
    partial void OnNhanThucChinhTriChanging(System.Nullable<decimal> value);
    partial void OnNhanThucChinhTriChanged();
    partial void OnChuyenMonNghiepVuChanging(System.Nullable<decimal> value);
    partial void OnChuyenMonNghiepVuChanged();
    partial void OnRenLuyenCaNhanChanging(System.Nullable<decimal> value);
    partial void OnRenLuyenCaNhanChanged();
    partial void OnLaBiThuChanging(System.Nullable<bool> value);
    partial void OnLaBiThuChanged();
    #endregion
		
		public DoanVien()
		{
			this._DangKies = new EntitySet<DangKy>(new Action<DangKy>(this.attach_DangKies), new Action<DangKy>(this.detach_DangKies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoDoan", DbType="Date NOT NULL")]
		public System.DateTime NgayVaoDoan
		{
			get
			{
				return this._NgayVaoDoan;
			}
			set
			{
				if ((this._NgayVaoDoan != value))
				{
					this.OnNgayVaoDoanChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoDoan = value;
					this.SendPropertyChanged("NgayVaoDoan");
					this.OnNgayVaoDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NChar(12)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiVaoDoan", DbType="NVarChar(500)")]
		public string NoiVaoDoan
		{
			get
			{
				return this._NoiVaoDoan;
			}
			set
			{
				if ((this._NoiVaoDoan != value))
				{
					this.OnNoiVaoDoanChanging(value);
					this.SendPropertyChanging();
					this._NoiVaoDoan = value;
					this.SendPropertyChanged("NoiVaoDoan");
					this.OnNoiVaoDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSSV", DbType="NChar(10)")]
		public string MSSV
		{
			get
			{
				return this._MSSV;
			}
			set
			{
				if ((this._MSSV != value))
				{
					this.OnMSSVChanging(value);
					this.SendPropertyChanging();
					this._MSSV = value;
					this.SendPropertyChanged("MSSV");
					this.OnMSSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XepLoai", DbType="Int NOT NULL")]
		public int XepLoai
		{
			get
			{
				return this._XepLoai;
			}
			set
			{
				if ((this._XepLoai != value))
				{
					this.OnXepLoaiChanging(value);
					this.SendPropertyChanging();
					this._XepLoai = value;
					this.SendPropertyChanged("XepLoai");
					this.OnXepLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanThucChinhTri", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> NhanThucChinhTri
		{
			get
			{
				return this._NhanThucChinhTri;
			}
			set
			{
				if ((this._NhanThucChinhTri != value))
				{
					this.OnNhanThucChinhTriChanging(value);
					this.SendPropertyChanging();
					this._NhanThucChinhTri = value;
					this.SendPropertyChanged("NhanThucChinhTri");
					this.OnNhanThucChinhTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenMonNghiepVu", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ChuyenMonNghiepVu
		{
			get
			{
				return this._ChuyenMonNghiepVu;
			}
			set
			{
				if ((this._ChuyenMonNghiepVu != value))
				{
					this.OnChuyenMonNghiepVuChanging(value);
					this.SendPropertyChanging();
					this._ChuyenMonNghiepVu = value;
					this.SendPropertyChanged("ChuyenMonNghiepVu");
					this.OnChuyenMonNghiepVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RenLuyenCaNhan", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RenLuyenCaNhan
		{
			get
			{
				return this._RenLuyenCaNhan;
			}
			set
			{
				if ((this._RenLuyenCaNhan != value))
				{
					this.OnRenLuyenCaNhanChanging(value);
					this.SendPropertyChanging();
					this._RenLuyenCaNhan = value;
					this.SendPropertyChanged("RenLuyenCaNhan");
					this.OnRenLuyenCaNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaBiThu", DbType="Bit")]
		public System.Nullable<bool> LaBiThu
		{
			get
			{
				return this._LaBiThu;
			}
			set
			{
				if ((this._LaBiThu != value))
				{
					this.OnLaBiThuChanging(value);
					this.SendPropertyChanging();
					this._LaBiThu = value;
					this.SendPropertyChanged("LaBiThu");
					this.OnLaBiThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoanVien_DangKy", Storage="_DangKies", ThisKey="ID", OtherKey="IDDoanVien")]
		public EntitySet<DangKy> DangKies
		{
			get
			{
				return this._DangKies;
			}
			set
			{
				this._DangKies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.DoanVien = this;
		}
		
		private void detach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.DoanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuKien")]
	public partial class SuKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten;
		
		private string _NoiDung;
		
		private string _DiaDiem;
		
		private System.DateTime _BatDau;
		
		private string _GhiChu;
		
		private EntitySet<DangKy> _DangKies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnBatDauChanging(System.DateTime value);
    partial void OnBatDauChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public SuKien()
		{
			this._DangKies = new EntitySet<DangKy>(new Action<DangKy>(this.attach_DangKies), new Action<DangKy>(this.detach_DangKies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatDau", DbType="DateTime NOT NULL")]
		public System.DateTime BatDau
		{
			get
			{
				return this._BatDau;
			}
			set
			{
				if ((this._BatDau != value))
				{
					this.OnBatDauChanging(value);
					this.SendPropertyChanging();
					this._BatDau = value;
					this.SendPropertyChanged("BatDau");
					this.OnBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuKien_DangKy", Storage="_DangKies", ThisKey="ID", OtherKey="IDSuKien")]
		public EntitySet<DangKy> DangKies
		{
			get
			{
				return this._DangKies;
			}
			set
			{
				this._DangKies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.SuKien = this;
		}
		
		private void detach_DangKies(DangKy entity)
		{
			this.SendPropertyChanging();
			entity.SuKien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuaAo")]
	public partial class MuaAo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDDoanVien;
		
		private int _SoLuong;
		
		private string _NoiDung;
		
		private System.DateTime _NgayThang;
		
		private int _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDDoanVienChanging(int value);
    partial void OnIDDoanVienChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayThangChanging(System.DateTime value);
    partial void OnNgayThangChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public MuaAo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDoanVien", DbType="Int NOT NULL")]
		public int IDDoanVien
		{
			get
			{
				return this._IDDoanVien;
			}
			set
			{
				if ((this._IDDoanVien != value))
				{
					this.OnIDDoanVienChanging(value);
					this.SendPropertyChanging();
					this._IDDoanVien = value;
					this.SendPropertyChanged("IDDoanVien");
					this.OnIDDoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThang", DbType="Date NOT NULL")]
		public System.DateTime NgayThang
		{
			get
			{
				return this._NgayThang;
			}
			set
			{
				if ((this._NgayThang != value))
				{
					this.OnNgayThangChanging(value);
					this.SendPropertyChanging();
					this._NgayThang = value;
					this.SendPropertyChanged("NgayThang");
					this.OnNgayThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeXuat")]
	public partial class DeXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDDoanVien;
		
		private string _NoiDung;
		
		private System.DateTime _NgayThang;
		
		private int _Loai;
		
		private string _NguoiDeXuat;
		
		private System.Nullable<int> _TrangThai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDDoanVienChanging(int value);
    partial void OnIDDoanVienChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayThangChanging(System.DateTime value);
    partial void OnNgayThangChanged();
    partial void OnLoaiChanging(int value);
    partial void OnLoaiChanged();
    partial void OnNguoiDeXuatChanging(string value);
    partial void OnNguoiDeXuatChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public DeXuat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDoanVien", DbType="Int NOT NULL")]
		public int IDDoanVien
		{
			get
			{
				return this._IDDoanVien;
			}
			set
			{
				if ((this._IDDoanVien != value))
				{
					this.OnIDDoanVienChanging(value);
					this.SendPropertyChanging();
					this._IDDoanVien = value;
					this.SendPropertyChanged("IDDoanVien");
					this.OnIDDoanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThang", DbType="Date NOT NULL")]
		public System.DateTime NgayThang
		{
			get
			{
				return this._NgayThang;
			}
			set
			{
				if ((this._NgayThang != value))
				{
					this.OnNgayThangChanging(value);
					this.SendPropertyChanging();
					this._NgayThang = value;
					this.SendPropertyChanged("NgayThang");
					this.OnNgayThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Int NOT NULL")]
		public int Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDeXuat", DbType="NVarChar(MAX)")]
		public string NguoiDeXuat
		{
			get
			{
				return this._NguoiDeXuat;
			}
			set
			{
				if ((this._NguoiDeXuat != value))
				{
					this.OnNguoiDeXuatChanging(value);
					this.SendPropertyChanging();
					this._NguoiDeXuat = value;
					this.SendPropertyChanged("NguoiDeXuat");
					this.OnNguoiDeXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class DoanVien_Get_SuKienResult
	{
		
		private int _ID;
		
		private string _Ten;
		
		private string _NoiDung;
		
		private string _DiaDiem;
		
		private System.DateTime _BatDau;
		
		private string _GhiChu;
		
		private System.Nullable<int> _TrangThai;
		
		public DoanVien_Get_SuKienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatDau", DbType="DateTime NOT NULL")]
		public System.DateTime BatDau
		{
			get
			{
				return this._BatDau;
			}
			set
			{
				if ((this._BatDau != value))
				{
					this._BatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
